name= "pastebin-worker"
compatibility_date = "2023-11-28"
account_id= "22812d251a775438597b379aebc4b330"
main = "src/index.ts"
workers_dev = false

vars = { ENVIRONMENT = "production" }
route = { pattern = "paste.wujingbo12.workers.dev", custom_domain = true }

kv_namespaces = [
  { binding = "PB", id = "a223dad5452241bc99b8fd6be5e3c3b7" },
  { binding = "PBIMGS", id ="f718cd7d189c4119916f767150d10d60 }
]

[site]
bucket = "./static/dist"
